##### ################################################################
#####
#####  Ghost
#####
##### ################################################################
FROM renshi/opensuse-tumbleweed-slime

MAINTAINER Renshi <yanqirenshi@gmail.com>

# Switch User
USER cl-user
WORKDIR /home/cl-user
